### ISSUE TITLE
Please update GameRig to work with Blender 4.1 bone collections

### ISSUE THREAD

**Issue by 3dcinetv** [Arminando/GameRig#33]
Hello, the last update for the addon mentions it works with Blender 3.6 (bone layers).
Can it be upgraded to work with BONE COLLECTIONS as required in Blender 4.1-4.2, please?

**Comment by Arminando** [comment]
Hello, the update will happen in the next weeks.
It takes a bit longer because only after I released this extension did I realize how tricky it is to maintain it due to changes that happen to rigify with every version.
So I am working on simplyfing things somehow so I don't have to rewrite half of the extension every time a blender update comes out.
Thank you for your patience. Once the update is out I would appreciate some feedback on it and the extension in general.
